### ISSUE TITLE
Thank you for using ZnTrack

### ISSUE THREAD

**Issue by PythonFZ** [mjcurran/JEMZnTrack#12]
Hi Matthew,

I am the main developer of ZnTrack and just recently stumbled across your project.
I am still overwhelmed when I see the effort you put into `JEMZnTrack` including the documentation.

First of all, I would like to apologize for the API break caused by switching from `@Node` decorator to class inheritance method. 
I didn`t expect anyone outside of my small circle of colleagues to use ZnTrack, and probably would have made more of an effort to keep it backwards compatible if I had known at the time. On the other hand, I hope you share our impression that a class inheritance method without hidden attributes and magic arguments gives ZnTrack a more mature feel. 

While I was reading through your documentation in amazement, I also noticed the problems for which you wrote workarounds.
I have already started working on some of them https://github.com/zincware/ZnTrack/pull/223 and hope that I will also be able to reproduce and fix the bug associated with

```
AttributeError: 'NoneType' object does not have attribute 'znjson_zn_method'
```

If there are any features you miss, or parts of ZnTrack you have issues with, or think would benefit from an API optimization, you are welcome to leave an issue in the ZnTrack repository.

We are in the process of rolling out ZnTrack to more colleagues working on simulations and machine learning, and will do everything we can to avoid further changes to the API.

Reading through your documentation, I am curious if you are developing it for yourself or if there is a broader community that will use your work?

All the best,
Fabian

**Comment by mjcurran** [comment]
Hi Fabian, I wasn't expecting anyone outside of my department to see that, so I'm glad the response was favorable.  
The docs are also published for easier reading at:  https://jemzntrack.readthedocs.io/en/latest/

I work for the Center for Research Computing at the University of Notre Dame, and this project is meant to be a set of examples for students researching machine learning, or applying ML to research, who may not necessarily be computer science majors.  The goal was to provide a sort of framework to help them organize projects and data while working mainly in jupyter notebooks, so that's why ZnTrack appealed to us.  I also really like the constraint of keeping all the managed code in classes, because the typical student written code in jupyter lab tends to be total throw-away code that's hard to re-use in any way, which I believe the original files in this example were, I didn't create it from scratch.

I agree with you that class inheritance is nicer than annotations, and prefer v0.3 of ZnTrack.  It's only poor timing on my part that necessitated including specific instructions for both versions in my docs, and partially limitations on our shared GPU cluster.

Thank you for your feedback and questions.  I just had a glance at your issue 223, and it looks like you're already adding features I would've requested, that's amazing, thank you again.  I will let you know if any other issues come up.

Thanks,
-Matthew Curran

P.S.  Do you pronounce it as "Zinc Track" internally?  I'd like to note that for students if it's official.

**Comment by PythonFZ** [comment]
Hi Matthew, 

that is great to hear. I did not foresee ZnTrack (Zinc Track) being used for educational purposes any time soon.
The feedback you get and the experience you made yourself are very valuable to me, so always feel free to share them in an issue or make a feature request.

I'm also working on a way to directly import Nodes from Jupyter Notebooks without creating the file in `src` but there are still some issues with it https://github.com/zincware/ZnTrack/pull/224 but it is something you can look forward to I'm going to make this an experimental feature for a start, which can be enabled in some way so that there are no API breaks.

Furhtermore, I checked the Python 3.7 support and unfortunately some tests are failing on windows, but I might be able to solve that and make the next release compatible with Python 3.7 again.

I wish you good luck and look forward to any feedback,
~Fabian Zills
